namespace Glacier.ML.Compute;

internal static class GpuMlKernels
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	kmeans_assign_fp32

.visible .entry kmeans_assign_fp32(
	.param .u64 kmeans_assign_fp32_param_0,
	.param .u64 kmeans_assign_fp32_param_1,
	.param .u64 kmeans_assign_fp32_param_2,
	.param .u32 kmeans_assign_fp32_param_3,
	.param .u32 kmeans_assign_fp32_param_4,
	.param .u32 kmeans_assign_fp32_param_5
)
{
	.reg .pred 	%p<17>;
	.reg .f32 	%f<54>;
	.reg .b32 	%r<66>;
	.reg .b64 	%rd<30>;


	ld.param.u64 	%rd15, [kmeans_assign_fp32_param_0];
	ld.param.u64 	%rd16, [kmeans_assign_fp32_param_1];
	ld.param.u64 	%rd14, [kmeans_assign_fp32_param_2];
	ld.param.u32 	%r34, [kmeans_assign_fp32_param_3];
	ld.param.u32 	%r32, [kmeans_assign_fp32_param_4];
	ld.param.u32 	%r33, [kmeans_assign_fp32_param_5];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	mov.u32 	%r35, %ctaid.x;
	mov.u32 	%r36, %ntid.x;
	mov.u32 	%r37, %tid.x;
	mad.lo.s32 	%r1, %r36, %r35, %r37;
	setp.ge.s32 	%p1, %r1, %r34;
	@%p1 bra 	$L__BB0_18;

	mul.lo.s32 	%r39, %r1, %r33;
	cvt.s64.s32 	%rd3, %r39;
	setp.lt.s32 	%p2, %r32, 1;
	mov.u32 	%r65, 0;
	@%p2 bra 	$L__BB0_17;

	setp.gt.s32 	%p3, %r33, 0;
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_3;

$L__BB0_8:
	add.s32 	%r19, %r33, -1;
	and.b32  	%r20, %r33, 3;
	sub.s32 	%r21, %r33, %r20;
	shl.b64 	%rd17, %rd3, 2;
	add.s64 	%rd18, %rd2, %rd17;
	add.s64 	%rd4, %rd18, 8;
	add.s64 	%rd5, %rd1, 8;
	mov.u32 	%r47, 0;
	mov.f32 	%f49, 0f7F7FFFFF;
	mov.u32 	%r60, %r47;
	mov.u32 	%r65, %r47;

$L__BB0_9:
	mul.lo.s32 	%r49, %r60, %r33;
	cvt.s64.s32 	%rd6, %r49;
	setp.lt.u32 	%p10, %r19, 3;
	mov.f32 	%f53, 0f00000000;
	mov.u32 	%r64, %r47;
	@%p10 bra 	$L__BB0_12;

	shl.b64 	%rd19, %rd6, 2;
	add.s64 	%rd28, %rd5, %rd19;
	mov.f32 	%f53, 0f00000000;
	mov.u32 	%r64, 0;
	mov.u64 	%rd29, %rd4;
	mov.u32 	%r63, %r21;

$L__BB0_11:
	ld.global.nc.f32 	%f22, [%rd28+-8];
	ld.global.nc.f32 	%f23, [%rd29+-8];
	sub.f32 	%f24, %f23, %f22;
	fma.rn.f32 	%f25, %f24, %f24, %f53;
	ld.global.nc.f32 	%f26, [%rd28+-4];
	ld.global.nc.f32 	%f27, [%rd29+-4];
	sub.f32 	%f28, %f27, %f26;
	fma.rn.f32 	%f29, %f28, %f28, %f25;
	ld.global.nc.f32 	%f30, [%rd28];
	ld.global.nc.f32 	%f31, [%rd29];
	sub.f32 	%f32, %f31, %f30;
	fma.rn.f32 	%f33, %f32, %f32, %f29;
	ld.global.nc.f32 	%f34, [%rd28+4];
	ld.global.nc.f32 	%f35, [%rd29+4];
	sub.f32 	%f36, %f35, %f34;
	fma.rn.f32 	%f53, %f36, %f36, %f33;
	add.s32 	%r64, %r64, 4;
	add.s64 	%rd29, %rd29, 16;
	add.s64 	%rd28, %rd28, 16;
	add.s32 	%r63, %r63, -4;
	setp.ne.s32 	%p11, %r63, 0;
	@%p11 bra 	$L__BB0_11;

$L__BB0_12:
	setp.eq.s32 	%p12, %r20, 0;
	@%p12 bra 	$L__BB0_16;

	setp.eq.s32 	%p13, %r20, 1;
	cvt.s64.s32 	%rd20, %r64;
	add.s64 	%rd21, %rd20, %rd3;
	shl.b64 	%rd22, %rd21, 2;
	add.s64 	%rd12, %rd2, %rd22;
	add.s64 	%rd23, %rd20, %rd6;
	shl.b64 	%rd24, %rd23, 2;
	add.s64 	%rd13, %rd1, %rd24;
	ld.global.nc.f32 	%f37, [%rd13];
	ld.global.nc.f32 	%f38, [%rd12];
	sub.f32 	%f39, %f38, %f37;
	fma.rn.f32 	%f53, %f39, %f39, %f53;
	@%p13 bra 	$L__BB0_16;

	setp.eq.s32 	%p14, %r20, 2;
	ld.global.nc.f32 	%f40, [%rd13+4];
	ld.global.nc.f32 	%f41, [%rd12+4];
	sub.f32 	%f42, %f41, %f40;
	fma.rn.f32 	%f53, %f42, %f42, %f53;
	@%p14 bra 	$L__BB0_16;

	ld.global.nc.f32 	%f43, [%rd13+8];
	ld.global.nc.f32 	%f44, [%rd12+8];
	sub.f32 	%f45, %f44, %f43;
	fma.rn.f32 	%f53, %f45, %f45, %f53;

$L__BB0_16:
	setp.lt.f32 	%p15, %f53, %f49;
	selp.b32 	%r65, %r60, %r65, %p15;
	selp.f32 	%f49, %f53, %f49, %p15;
	add.s32 	%r60, %r60, 1;
	setp.lt.s32 	%p16, %r60, %r32;
	@%p16 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_17;

$L__BB0_3:
	add.s32 	%r43, %r32, -1;
	and.b32  	%r59, %r32, 3;
	setp.lt.u32 	%p4, %r43, 3;
	mov.u32 	%r55, 0;
	mov.f32 	%f47, 0f7F7FFFFF;
	mov.u32 	%r65, %r55;
	@%p4 bra 	$L__BB0_6;

	sub.s32 	%r53, %r32, %r59;
	mov.u32 	%r55, 0;
	mov.f32 	%f47, 0f7F7FFFFF;

$L__BB0_5:
	setp.gt.f32 	%p5, %f47, 0f00000000;
	selp.b32 	%r65, %r55, %r65, %p5;
	selp.f32 	%f47, 0f00000000, %f47, %p5;
	add.s32 	%r55, %r55, 4;
	add.s32 	%r53, %r53, -4;
	setp.ne.s32 	%p6, %r53, 0;
	@%p6 bra 	$L__BB0_5;

$L__BB0_6:
	setp.eq.s32 	%p7, %r59, 0;
	@%p7 bra 	$L__BB0_17;

$L__BB0_7:
	.pragma ""nounroll"";
	setp.gt.f32 	%p8, %f47, 0f00000000;
	selp.b32 	%r65, %r55, %r65, %p8;
	selp.f32 	%f47, 0f00000000, %f47, %p8;
	add.s32 	%r55, %r55, 1;
	add.s32 	%r59, %r59, -1;
	setp.eq.s32 	%p9, %r59, 0;
	@%p9 bra 	$L__BB0_17;
	bra.uni 	$L__BB0_7;

$L__BB0_17:
	cvta.to.global.u64 	%rd25, %rd14;
	mul.wide.s32 	%rd26, %r1, 4;
	add.s64 	%rd27, %rd25, %rd26;
	st.global.u32 	[%rd27], %r65;

$L__BB0_18:
	ret;

}
	// .globl	vector_sigmoid_fp32
.visible .entry vector_sigmoid_fp32(
	.param .u64 vector_sigmoid_fp32_param_0,
	.param .u64 vector_sigmoid_fp32_param_1,
	.param .f32 vector_sigmoid_fp32_param_2,
	.param .u32 vector_sigmoid_fp32_param_3
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<8>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd2, [vector_sigmoid_fp32_param_0];
	ld.param.u64 	%rd3, [vector_sigmoid_fp32_param_1];
	ld.param.f32 	%f2, [vector_sigmoid_fp32_param_2];
	ld.param.u32 	%r2, [vector_sigmoid_fp32_param_3];
	mov.u32 	%r3, %ctaid.x;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r4, %r3, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB1_6;

	cvta.to.global.u64 	%rd4, %rd2;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f3, [%rd6];
	add.f32 	%f1, %f3, %f2;
	setp.gt.f32 	%p2, %f1, 0f41A00000;
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd1, %rd7, %rd5;
	@%p2 bra 	$L__BB1_5;
	bra.uni 	$L__BB1_2;

$L__BB1_5:
	mov.u32 	%r7, 1065353216;
	st.global.u32 	[%rd1], %r7;
	bra.uni 	$L__BB1_6;

$L__BB1_2:
	setp.lt.f32 	%p3, %f1, 0fC1A00000;
	@%p3 bra 	$L__BB1_4;
	bra.uni 	$L__BB1_3;

$L__BB1_4:
	mov.u32 	%r6, 0;
	st.global.u32 	[%rd1], %r6;
	bra.uni 	$L__BB1_6;

$L__BB1_3:
	mul.f32 	%f4, %f1, 0fBFB8AA3B;
	ex2.approx.f32 	%f5, %f4;
	add.f32 	%f6, %f5, 0f3F800000;
	rcp.rn.f32 	%f7, %f6;
	st.global.f32 	[%rd1], %f7;

$L__BB1_6:
	ret;

}

";
}
